"""add color to groups

Revision ID: 764e136c99da
Revises: 38e297322eac
Create Date: 2026-04-30 15:05:01.298191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764e136c99da'
down_revision: Union[str, Sequence[str], None] = '38e297322eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('income_expense_groups', sa.Column('color', sa.String(length=20), nullable=True))
    op.execute("UPDATE income_expense_groups SET color = '#6b7280' WHERE color IS NULL")
    op.alter_column('income_expense_groups', 'color', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income_expense_groups', 'color')
    # ### end Alembic commands ###
